# Generated by Django 2.1.15 on 2020-04-23 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Area')),
            ],
            options={
                'verbose_name': 'Sheet Details',
                'verbose_name_plural': 'Sheet Details',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Final Bill',
                'verbose_name_plural': 'Final Bills',
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('nos', 'NOS'), ('meter', 'MTRS'), ('feet', 'FEET')], max_length=5)),
                ('prize', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Company')),
            ],
            options={
                'verbose_name': 'Bill Details',
                'verbose_name_plural': 'Bill Details',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Products'),
        ),
        migrations.AddField(
            model_name='bills',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.ProductDetails'),
        ),
    ]
