# Generated by Django 2.1.15 on 2020-04-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('logo', models.ImageField(upload_to='pic_folder/')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=13)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='unit',
            field=models.CharField(choices=[('NOS', 'NOS'), ('MTRS', 'MTRS'), ('FEET', 'FEET')], max_length=5),
        ),
    ]
