# Generated by Django 2.1.15 on 2020-04-25 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20200425_0302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanySetting',
        ),
    ]
