# Generated by Django 2.1.15 on 2020-04-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_delete_companysetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('logo', models.ImageField(upload_to='pic_folder/')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=13)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
